### PR TITLE
feat(build)!: use common build process

### PR DESCRIPTION
**Pull request by Thomaash**
BREAKING CHANGE: The old bundles are no longer present in the package. It has to be replaced by `import * as util from 'vis-util/esnext';`. I'll do that in all of our projects so don't bother updating to this, it most likely won't work anyway.

The build process from https://github.com/visjs/vis-dev-utils/pull/10 is finally being deployed :tada:.

I also increased the timeout of some tests because they kept failing solely due to not having enough of time to finish.

### CODE REVIEW

**Comment by yotamberk** [comment]
@Thomaash Are you going to submit PRs for the rest of the libraries to work again with this update?
Do you need my help with this?

**Comment by Thomaash** [comment]
I don't have much time at the moment and won't have the next week either so if you could help that would be great. When I submitted the Vis Data PR I had a working copy locally. In theory it should be enough to just rebase it on top of master (or merge) and it should work. I'll push it to GitHub so that if you find the time you can work on it.

**Comment by yotamberk** [comment]
I try to add what you did to all the `/esnext` to `vis-data` and `vis-util` imports but seem to get problems with the test now. I managed to solve it via adding `mocha -r esm ...` and to install `esm` as a dev dependency.
the thing is, everything seems to work even when I don't add `/esnext` to the imports. Are you sure it's needed?

**Comment by Thomaash** [comment]
The purpose of the /esnext is to reuse polyfills from the main project. That is to use the polyfills from for example Vis Timeline also in Vis Data and Vis Util. Otherwise the same polyfills would be included multiple times leading to bundle bloat. The tests have to use Babel to polyfill it on the go. There is a register exported by Vis Dev Utils for it (`vis-dev-utils/babel-register`).

**Comment by Thomaash** [comment]
I managed to get an extension on my article's deadline and since I no longer have to rush it in just a few days I dedicated this evening to get this thing working. It wasn't as simple as rebasing after all.

**Pull request merged**
